insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('4444 3333 2222 1111', 'João do Brasil', 'João da Silva do Brasil', '23.567.234-0', 'Maria da Silva do Brasil', 'Rua do Brasil', 'São Paulo');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('1111 2222 3333 4444', 'Maria da França', 'Maria da Silva do França', '23.567.234-0', 'Maria da Silva da França', 'Rua da França', 'Paris');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('2222 3333 4444 5555', 'José da Alemanha', 'José da Silva da Alemanha', '23.567.234-0', 'Maria da Silva da Alemanha', 'Rua da Alemanha', 'Berlim');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('3333 4444 5555 6666', 'Carlos da Argentina', 'Carlos da Silva da Argentina', '23.567.234-0', 'Maria da Silva da Argentina', 'Rua da Argentina', 'Buenos Aires');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('5555 6666 7777 8888', 'Francisco do México', 'Francisco da Silva do México', '23.567.234-0', 'Maria da Silva do México', 'Rua do México', 'Cidade do México');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('6666 7777 8888 9999', 'Fernanda de Portugal', 'Fernanda da Silva de Portugal', '23.567.234-0', 'Maria da Silva de Portugal', 'Rua de Portugal', 'Lisboa');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('7777 8888 9999 1111', 'Zoe de Cuba', 'Zoe da Silva de Cuba', '23.567.234-0', 'Maria da Silva de Cuba', 'Rua de Cuba', 'Havana');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('8888 9999 0000 1111', 'Jade de Senegal', 'Jade da Silva de Senegal', '23.567.234-0', 'Maria da Silva de Senegal', 'Rua do Senegal', 'Dacar');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('9999 0000 1111 2222', 'Pablo da Espanha', 'Pablo da Silva do Espanha', '23.567.234-0', 'Maria da Silva do Espanha', 'Rua da Espanha', 'Madrid');                
insert into tb_card(card_Number, emboss_Name, customer_Name, document_Number, mother_Name, address, city ) values ('0000 1111 2222 3333', 'Diego do Uruguai', 'Diego da Silva do Uruguai', '23.567.234-0', 'Maria da Silva do Uruguai', 'Rua do Uruguai', 'Montevidéu');                



